# Generated by Django 5.0.7 on 2024-08-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregister',
            name='businessAddress',
        ),
        migrations.RemoveField(
            model_name='eventregister',
            name='businessName',
        ),
        migrations.RemoveField(
            model_name='eventregister',
            name='organizationName',
        ),
    ]
