# Generated by Django 5.0.7 on 2024-08-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_eventregister_businessaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregister',
            name='paymentStatus',
            field=models.CharField(default='not made', max_length=50),
        ),
    ]
